# Description: Configuration file to sample from the QM9 dataset with combinatorial complexes using CCSD

is_cc: True

data:
  data: QM9
  dir: './data'
  max_node_num: 9
  min_node_val: 6
  max_node_val: 9
  node_label: symbol
  min_edge_val: 1
  max_edge_val: 3
  edge_label: bond_type
  d_min: 3
  d_max: 9

ckpt: ccsd_qm9_Base_CC

sampler:
  predictor: Reverse
  corrector: Langevin
  snr: 0.2
  scale_eps: 0.7
  n_steps: 1

sample:
  divide_batch: 2  # optional, only if RAM issue occurs
  n_samples: 10000  # param only for mol datasets
  cc_nb_eval: 1000  # param only for cc datasets
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 42
