# Description: Configuration file to sample from the QM9 dataset with combinatorial complexes used in our work CDSS

is_cc: True

data:
  data: QM9
  dir: './data'
  d_min: 3
  d_max: 9

ckpt: gdss_qm9_cc

sampler:
  predictor: Reverse
  corrector: Langevin
  snr: 0.2
  scale_eps: 0.7
  n_steps: 1

sample:
  n_samples: 10000  # param only for mol datasets
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 42
